Fix error in 0b2834e9bb7344b1516eabd05314fc9c2357290c
Restores it as a collection, instead of a scalar.

Fixes the error:

```
  File "/work/src/shop/transactions.py", line 87, in get_source_transaction
    .filter(Transaction.stripe_pending.any(StripePending.stripe_token == source_id))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
sqlalchemy.exc.InvalidRequestError: 'any()' not implemented for scalar attributes. Use has().
```